title: Ben Turner Portfolio
logo: IMG_9255.png
banner: IMG_6511.jpeg
# description: Hello! My name is Ben, and I am an experienced author and publishing professional with over 5 years of proven expertise in publication and editing. With skills in Google Docs, Microsoft Word, InDesign, and Photoshop, I can edit and design books to achieve a professional final product. I am adept with Adobeâ€™s suite, various word processors, and Microsoft/Apple hardware. My creative skill set, commitment to professionalism, and passion for fiction writing make me a valuable asset. In my spare time, I like listening to a wide range of music genres and playing competitive video games. You can find me on LinkedIn, Instagram, or Facebook.
# show_downloads: true
theme: jekyll-theme-minimal
